### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by capndave** [blackbeam/poppler-simple#21]
I'm using Node v8.11.3 and npm v6.4.1. On `npm i --save poppler-simple`, I get
```
> poppler-simple@0.3.0 preinstall /home/dave/Documents/print-server/node_modules/poppler-simple
> ((npm install nan) && (node-gyp configure)) || (exit 0)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN poppler-simple@0.3.0 No license field.

+ nan@2.11.1
added 1 package from 8 contributors and audited 1 package in 0.741s
found 0 vulnerabilities


> poppler-simple@0.3.0 install /home/dave/Documents/print-server/node_modules/poppler-simple
> (node-gyp rebuild) || (exit 1)

make: Entering directory '/home/dave/Documents/print-server/node_modules/poppler-simple/build'
  CXX(target) Release/obj.target/poppler/src/poppler.o
In file included from ../src/poppler.cc:3:0:
../src/NodePopplerDocument.h:4:26: fatal error: GlobalParams.h: No such file or directory
compilation terminated.
poppler.target.mk:113: recipe for target 'Release/obj.target/poppler/src/poppler.o' failed
make: *** [Release/obj.target/poppler/src/poppler.o] Error 1
make: Leaving directory '/home/dave/Documents/print-server/node_modules/poppler-simple/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dave/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/home/dave/.nvm/versions/node/v8.11.3/bin/node" "/home/dave/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dave/Documents/print-server/node_modules/poppler-simple
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN print-server@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poppler-simple@0.3.0 install: `(node-gyp rebuild) || (exit 1)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poppler-simple@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dave/.npm/_logs/2018-09-30T20_47_26_054Z-debug.log
```
### Error Log### 
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/dave/.nvm/versions/node/v8.11.3/bin/node',
1 verbose cli   '/home/dave/.nvm/versions/node/v8.11.3/bin/npm',
1 verbose cli   'i',
1 verbose cli   '--save',
1 verbose cli   'calipers',
1 verbose cli   'calipers-pdf' ]
2 info using npm@6.4.1
3 info using node@v8.11.3
4 verbose npm-session e2f42067e0791cac
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/calipers-pdf 9ms (from cache)
8 http fetch GET 200 https://registry.npmjs.org/calipers 12ms (from cache)
9 silly pacote tag manifest for calipers@latest fetched in 19ms
10 silly pacote tag manifest for calipers-pdf@latest fetched in 11ms
11 timing stage:loadCurrentTree Completed in 269ms
12 silly install loadIdealTree
13 silly install cloneCurrentTreeToIdealTree
14 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
15 silly install loadShrinkwrap
16 timing stage:loadIdealTree:loadShrinkwrap Completed in 74ms
17 silly install loadAllDepsIntoIdealTree
18 silly resolveWithNewModule calipers@2.0.1 checking installable status
19 silly resolveWithNewModule calipers-pdf@2.0.0 checking installable status
20 http fetch GET 200 https://registry.npmjs.org/bluebird 3ms (from cache)
21 silly pacote range manifest for bluebird@3.x.x fetched in 7ms
22 silly resolveWithNewModule bluebird@3.5.2 checking installable status
23 http fetch GET 200 https://registry.npmjs.org/poppler-simple 2ms (from cache)
24 silly pacote range manifest for poppler-simple@0.2.x fetched in 3ms
25 silly resolveWithNewModule poppler-simple@0.2.9 checking installable status
26 http fetch GET 200 https://registry.npmjs.org/nan 2ms (from cache)
27 silly pacote range manifest for nan@^2.7.0 fetched in 2ms
28 silly resolveWithNewModule nan@2.11.1 checking installable status
29 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 88ms
30 timing stage:loadIdealTree Completed in 187ms
31 silly currentTree print-server@1.0.0
31 silly currentTree ├── @types/core-js@0.9.46
31 silly currentTree ├── @types/mkdirp@0.3.29
31 silly currentTree ├── @types/node@9.6.32
31 silly currentTree ├── @types/rimraf@0.0.28
31 silly currentTree ├── assert-plus@1.0.0
31 silly currentTree ├── async-limiter@1.0.0
31 silly currentTree ├── async@2.6.1
31 silly currentTree ├── axios@0.18.0
31 silly currentTree ├── babel-runtime@6.26.0
31 silly currentTree ├── balanced-match@1.0.0
31 silly currentTree ├── big-number@0.3.1
31 silly currentTree ├── bl@1.2.2
31 silly currentTree ├── bluebird@3.5.2
31 silly currentTree ├── brace-expansion@1.1.11
31 silly currentTree ├── calipers@2.0.1
31 silly currentTree ├── chrome-launcher@0.10.5
31 silly currentTree ├── chrome-remote-interface@0.25.7
31 silly currentTree ├── color-convert@1.9.3
31 silly currentTree ├── color-name@1.1.3
31 silly currentTree ├── color-string@1.5.3
31 silly currentTree ├── color@3.0.0
31 silly currentTree ├── colornames@1.1.1
31 silly currentTree ├── colors@1.3.2
31 silly currentTree ├── colorspace@1.1.1
31 silly currentTree ├── commander@2.11.0
31 silly currentTree ├── concat-map@0.0.1
31 silly currentTree ├── core-js@2.5.7
31 silly currentTree ├── core-util-is@1.0.2
31 silly currentTree ├── debug@3.1.0
31 silly currentTree ├── depd@1.1.2
31 silly currentTree ├── diagnostics@1.1.1
31 silly currentTree ├── enabled@1.0.2
31 silly currentTree ├── env-variable@0.0.4
31 silly currentTree ├── extsprintf@1.4.0
31 silly currentTree ├── fast-safe-stringify@2.0.6
31 silly currentTree ├── fecha@2.3.3
31 silly currentTree ├── follow-redirects@1.5.8
31 silly currentTree ├── fs.realpath@1.0.0
31 silly currentTree ├── generic-pool@3.4.2
31 silly currentTree ├── glob@7.1.3
31 silly currentTree ├── handlebars@4.0.12
31 silly currentTree ├── html-pdf-chrome@0.5.0
31 silly currentTree ├── iconv-lite@0.2.11
31 silly currentTree ├── inflight@1.0.6
31 silly currentTree ├── inherits@2.0.3
31 silly currentTree ├── is-arrayish@0.3.2
31 silly currentTree ├── is-buffer@1.1.6
31 silly currentTree ├── is-stream@1.1.0
31 silly currentTree ├── is-wsl@1.1.0
31 silly currentTree ├── isarray@1.0.0
31 silly currentTree ├── kuler@1.0.0
31 silly currentTree ├─┬ lighthouse-logger@1.1.0
31 silly currentTree │ └── debug@2.6.9
31 silly currentTree ├── lodash@4.17.11
31 silly currentTree ├─┬ logform@1.10.0
31 silly currentTree │ └── ms@2.1.1
31 silly currentTree ├── marky@1.2.0
31 silly currentTree ├── minimatch@3.0.4
31 silly currentTree ├── minimist@0.0.8
31 silly currentTree ├── mkdirp@0.5.1
31 silly currentTree ├── ms@2.0.0
31 silly currentTree ├── mssql@4.2.1
31 silly currentTree ├── native-duplexpair@1.0.0
31 silly currentTree ├── once@1.4.0
31 silly currentTree ├── one-time@0.0.4
31 silly currentTree ├── optimist@0.6.1
31 silly currentTree ├── path-is-absolute@1.0.1
31 silly currentTree ├── process-nextick-args@2.0.0
31 silly currentTree ├── punycode@2.1.1
31 silly currentTree ├── qs@1.2.0
31 silly currentTree ├── readable-stream@2.3.6
31 silly currentTree ├── regenerator-runtime@0.11.1
31 silly currentTree ├── restler@3.4.0
31 silly currentTree ├── rimraf@2.6.2
31 silly currentTree ├── safe-buffer@5.1.2
31 silly currentTree ├── safer-buffer@2.1.2
31 silly currentTree ├── sax@0.5.8
31 silly currentTree ├── simple-swizzle@0.2.2
31 silly currentTree ├── source-map@0.6.1
31 silly currentTree ├── sprintf-js@1.1.1
31 silly currentTree ├── stack-trace@0.0.10
31 silly currentTree ├── string_decoder@1.1.1
31 silly currentTree ├─┬ tedious@2.6.4
31 silly currentTree │ └── iconv-lite@0.4.24
31 silly currentTree ├── text-hex@1.0.0
31 silly currentTree ├── triple-beam@1.3.0
31 silly currentTree ├─┬ uglify-js@3.4.9
31 silly currentTree │ └── commander@2.17.1
31 silly currentTree ├── ultron@1.1.1
31 silly currentTree ├── util-deprecate@1.0.2
31 silly currentTree ├── vasync@2.2.0
31 silly currentTree ├── verror@1.10.0
31 silly currentTree ├── winston-transport@4.2.0
31 silly currentTree ├── winston@3.1.0
31 silly currentTree ├── wordwrap@0.0.3
31 silly currentTree ├── wrappy@1.0.2
31 silly currentTree ├── ws@3.3.2
31 silly currentTree ├── xml2js@0.4.0
31 silly currentTree ├── xmlbuilder@10.0.0
31 silly currentTree └── yaml@0.2.3
32 silly idealTree print-server@1.0.0
32 silly idealTree ├── @types/core-js@0.9.46
32 silly idealTree ├── @types/mkdirp@0.3.29
32 silly idealTree ├── @types/node@9.6.32
32 silly idealTree ├── @types/rimraf@0.0.28
32 silly idealTree ├── assert-plus@1.0.0
32 silly idealTree ├── async-limiter@1.0.0
32 silly idealTree ├── async@2.6.1
32 silly idealTree ├── axios@0.18.0
32 silly idealTree ├── babel-runtime@6.26.0
32 silly idealTree ├── balanced-match@1.0.0
32 silly idealTree ├── big-number@0.3.1
32 silly idealTree ├── bl@1.2.2
32 silly idealTree ├── bluebird@3.5.2
32 silly idealTree ├── brace-expansion@1.1.11
32 silly idealTree ├── calipers-pdf@2.0.0
32 silly idealTree ├── calipers@2.0.1
32 silly idealTree ├── chrome-launcher@0.10.5
32 silly idealTree ├── chrome-remote-interface@0.25.7
32 silly idealTree ├── color-convert@1.9.3
32 silly idealTree ├── color-name@1.1.3
32 silly idealTree ├── color-string@1.5.3
32 silly idealTree ├── color@3.0.0
32 silly idealTree ├── colornames@1.1.1
32 silly idealTree ├── colors@1.3.2
32 silly idealTree ├── colorspace@1.1.1
32 silly idealTree ├── commander@2.11.0
32 silly idealTree ├── concat-map@0.0.1
32 silly idealTree ├── core-js@2.5.7
32 silly idealTree ├── core-util-is@1.0.2
32 silly idealTree ├── debug@3.1.0
32 silly idealTree ├── depd@1.1.2
32 silly idealTree ├── diagnostics@1.1.1
32 silly idealTree ├── enabled@1.0.2
32 silly idealTree ├── env-variable@0.0.4
32 silly idealTree ├── extsprintf@1.4.0
32 silly idealTree ├── fast-safe-stringify@2.0.6
32 silly idealTree ├── fecha@2.3.3
32 silly idealTree ├── follow-redirects@1.5.8
32 silly idealTree ├── fs.realpath@1.0.0
32 silly idealTree ├── generic-pool@3.4.2
32 silly idealTree ├── glob@7.1.3
32 silly idealTree ├── handlebars@4.0.12
32 silly idealTree ├── html-pdf-chrome@0.5.0
32 silly idealTree ├── iconv-lite@0.2.11
32 silly idealTree ├── inflight@1.0.6
32 silly idealTree ├── inherits@2.0.3
32 silly idealTree ├── is-arrayish@0.3.2
32 silly idealTree ├── is-buffer@1.1.6
32 silly idealTree ├── is-stream@1.1.0
32 silly idealTree ├── is-wsl@1.1.0
32 silly idealTree ├── isarray@1.0.0
32 silly idealTree ├── kuler@1.0.0
32 silly idealTree ├─┬ lighthouse-logger@1.1.0
32 silly idealTree │ └── debug@2.6.9
32 silly idealTree ├── lodash@4.17.11
32 silly idealTree ├─┬ logform@1.10.0
32 silly idealTree │ └── ms@2.1.1
32 silly idealTree ├── marky@1.2.0
32 silly idealTree ├── minimatch@3.0.4
32 silly idealTree ├── minimist@0.0.8
32 silly idealTree ├── mkdirp@0.5.1
32 silly idealTree ├── ms@2.0.0
32 silly idealTree ├── mssql@4.2.1
32 silly idealTree ├── nan@2.11.1
32 silly idealTree ├── native-duplexpair@1.0.0
32 silly idealTree ├── once@1.4.0
32 silly idealTree ├── one-time@0.0.4
32 silly idealTree ├── optimist@0.6.1
32 silly idealTree ├── path-is-absolute@1.0.1
32 silly idealTree ├── poppler-simple@0.2.9
32 silly idealTree ├── process-nextick-args@2.0.0
32 silly idealTree ├── punycode@2.1.1
32 silly idealTree ├── qs@1.2.0
32 silly idealTree ├── readable-stream@2.3.6
32 silly idealTree ├── regenerator-runtime@0.11.1
32 silly idealTree ├── restler@3.4.0
32 silly idealTree ├── rimraf@2.6.2
32 silly idealTree ├── safe-buffer@5.1.2
32 silly idealTree ├── safer-buffer@2.1.2
32 silly idealTree ├── sax@0.5.8
32 silly idealTree ├── simple-swizzle@0.2.2
32 silly idealTree ├── source-map@0.6.1
32 silly idealTree ├── sprintf-js@1.1.1
32 silly idealTree ├── stack-trace@0.0.10
32 silly idealTree ├── string_decoder@1.1.1
32 silly idealTree ├─┬ tedious@2.6.4
32 silly idealTree │ └── iconv-lite@0.4.24
32 silly idealTree ├── text-hex@1.0.0
32 silly idealTree ├── triple-beam@1.3.0
32 silly idealTree ├─┬ uglify-js@3.4.9
32 silly idealTree │ └── commander@2.17.1
32 silly idealTree ├── ultron@1.1.1
32 silly idealTree ├── util-deprecate@1.0.2
32 silly idealTree ├── vasync@2.2.0
32 silly idealTree ├── verror@1.10.0
32 silly idealTree ├── winston-transport@4.2.0
32 silly idealTree ├── winston@3.1.0
32 silly idealTree ├── wordwrap@0.0.3
32 silly idealTree ├── wrappy@1.0.2
32 silly idealTree ├── ws@3.3.2
32 silly idealTree ├── xml2js@0.4.0
32 silly idealTree ├── xmlbuilder@10.0.0
32 silly idealTree └── yaml@0.2.3
33 silly install generateActionsToTake
34 timing stage:generateActionsToTake Completed in 8ms
35 silly diffTrees action count 4
36 silly diffTrees add nan@2.11.1
37 silly diffTrees update calipers@2.0.1
38 silly diffTrees add poppler-simple@0.2.9
39 silly diffTrees add calipers-pdf@2.0.0
40 silly decomposeActions action count 34
41 silly decomposeActions fetch nan@2.11.1
42 silly decomposeActions extract nan@2.11.1
43 silly decomposeActions preinstall nan@2.11.1
44 silly decomposeActions build nan@2.11.1
45 silly decomposeActions install nan@2.11.1
46 silly decomposeActions postinstall nan@2.11.1
47 silly decomposeActions finalize nan@2.11.1
48 silly decomposeActions refresh-package-json nan@2.11.1
49 silly decomposeActions unbuild calipers@2.0.1
50 silly decomposeActions remove calipers@2.0.1
51 silly decomposeActions fetch calipers@2.0.1
52 silly decomposeActions extract calipers@2.0.1
53 silly decomposeActions preinstall calipers@2.0.1
54 silly decomposeActions build calipers@2.0.1
55 silly decomposeActions install calipers@2.0.1
56 silly decomposeActions postinstall calipers@2.0.1
57 silly decomposeActions finalize calipers@2.0.1
58 silly decomposeActions refresh-package-json calipers@2.0.1
59 silly decomposeActions fetch poppler-simple@0.2.9
60 silly decomposeActions extract poppler-simple@0.2.9
61 silly decomposeActions preinstall poppler-simple@0.2.9
62 silly decomposeActions build poppler-simple@0.2.9
63 silly decomposeActions install poppler-simple@0.2.9
64 silly decomposeActions postinstall poppler-simple@0.2.9
65 silly decomposeActions finalize poppler-simple@0.2.9
66 silly decomposeActions refresh-package-json poppler-simple@0.2.9
67 silly decomposeActions fetch calipers-pdf@2.0.0
68 silly decomposeActions extract calipers-pdf@2.0.0
69 silly decomposeActions preinstall calipers-pdf@2.0.0
70 silly decomposeActions build calipers-pdf@2.0.0
71 silly decomposeActions install calipers-pdf@2.0.0
72 silly decomposeActions postinstall calipers-pdf@2.0.0
73 silly decomposeActions finalize calipers-pdf@2.0.0
74 silly decomposeActions refresh-package-json calipers-pdf@2.0.0
75 silly install executeActions
76 silly doSerial global-install 34
77 verbose correctMkdir /home/dave/.npm/_locks correctMkdir not in flight; initializing
78 timing audit compress Completed in 2ms
79 info audit Submitting payload of 7387bytes
80 verbose lock using /home/dave/.npm/_locks/staging-6f19addd09a3193b.lock for /home/dave/Documents/print-server/node_modules/.staging
81 silly doParallel extract 4
82 silly extract nan@2.11.1
83 silly extract calipers@2.0.1
84 silly extract poppler-simple@0.2.9
85 silly extract calipers-pdf@2.0.0
86 silly tarball trying nan@^2.7.0 by hash: sha512-iji6k87OSXa0CcrLl9z+ZiYSuR2o+c0bGuNmXdrhTQTakxytAFsC56SArGYoiHlJlFoHSnvmhpceZJaXkVuOtA==
87 silly tarball trying calipers@latest by hash: sha512-AP4Ui2Z8fZf69d8Dx4cfJgPjQHY3m+QXGFCaAGu8pfNQjyajkosS+Kkf1n6pQDMZcelN5h3MdcjweUqxcsS4pg==
88 silly tarball trying poppler-simple@0.2.x by hash: sha512-ocKh61Zak4Qe+WJjsbly3JXMNZpIATLTmtopgJArTN4jNRdC/Y3SN+OMwvWogM/dsV5GvgztqjXJOdGm7hGQVA==
89 silly tarball trying calipers-pdf@latest by hash: sha1-H4IkbNE6uBe7SbRwkHoDjNH3blk=
90 silly extract poppler-simple@0.2.x extracted to /home/dave/Documents/print-server/node_modules/.staging/poppler-simple-40f31a91 (31ms)
91 silly extract calipers@latest extracted to /home/dave/Documents/print-server/node_modules/.staging/calipers-d7a6b5fc (33ms)
92 silly extract nan@^2.7.0 extracted to /home/dave/Documents/print-server/node_modules/.staging/nan-82ac1614 (51ms)
93 silly extract calipers-pdf@latest extracted to /home/dave/Documents/print-server/node_modules/.staging/calipers-pdf-f250ac49 (49ms)
94 timing action:extract Completed in 53ms
95 silly doReverseSerial unbuild 34
96 silly unbuild calipers@2.0.1
97 info lifecycle calipers@2.0.1~preuninstall: calipers@2.0.1
98 info lifecycle calipers@2.0.1~uninstall: calipers@2.0.1
99 verbose unbuild rmStuff calipers@2.0.1 from /home/dave/Documents/print-server/node_modules
100 info lifecycle calipers@2.0.1~postuninstall: calipers@2.0.1
101 timing action:unbuild Completed in 2ms
102 silly doSerial remove 34
103 silly remove /home/dave/Documents/print-server/node_modules/calipers
104 timing action:remove Completed in 5ms
105 silly doSerial move 34
106 silly doSerial finalize 34
107 silly finalize /home/dave/Documents/print-server/node_modules/nan
108 silly finalize /home/dave/Documents/print-server/node_modules/calipers
109 silly finalize /home/dave/Documents/print-server/node_modules/poppler-simple
110 silly finalize /home/dave/Documents/print-server/node_modules/calipers-pdf
111 timing action:finalize Completed in 2ms
112 silly doParallel refresh-package-json 4
113 silly refresh-package-json /home/dave/Documents/print-server/node_modules/nan
114 silly refresh-package-json /home/dave/Documents/print-server/node_modules/calipers
115 silly refresh-package-json /home/dave/Documents/print-server/node_modules/poppler-simple
116 silly refresh-package-json /home/dave/Documents/print-server/node_modules/calipers-pdf
117 timing action:refresh-package-json Completed in 7ms
118 silly doParallel preinstall 4
119 silly preinstall nan@2.11.1
120 info lifecycle nan@2.11.1~preinstall: nan@2.11.1
121 silly preinstall calipers@2.0.1
122 info lifecycle calipers@2.0.1~preinstall: calipers@2.0.1
123 silly preinstall poppler-simple@0.2.9
124 info lifecycle poppler-simple@0.2.9~preinstall: poppler-simple@0.2.9
125 silly preinstall calipers-pdf@2.0.0
126 info lifecycle calipers-pdf@2.0.0~preinstall: calipers-pdf@2.0.0
127 verbose lifecycle poppler-simple@0.2.9~preinstall: unsafe-perm in lifecycle true
128 verbose lifecycle poppler-simple@0.2.9~preinstall: PATH: /home/dave/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dave/Documents/print-server/node_modules/poppler-simple/node_modules/.bin:/home/dave/Documents/print-server/node_modules/.bin:/home/dave/.nvm/versions/node/v8.11.3/bin:/home/dave/bin:/home/dave/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
129 verbose lifecycle poppler-simple@0.2.9~preinstall: CWD: /home/dave/Documents/print-server/node_modules/poppler-simple
130 silly lifecycle poppler-simple@0.2.9~preinstall: Args: [ '-c',
130 silly lifecycle   '((npm install nan) && (node-gyp configure)) || (exit 0)' ]
131 timing audit submit Completed in 550ms
132 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 549ms
133 timing audit body Completed in 1ms
134 silly lifecycle poppler-simple@0.2.9~preinstall: Returned: code: 0  signal: null
135 timing action:preinstall Completed in 1338ms
136 silly doSerial build 34
137 silly build nan@2.11.1
138 info linkStuff nan@2.11.1
139 silly linkStuff nan@2.11.1 has /home/dave/Documents/print-server/node_modules as its parent node_modules
140 silly build calipers@2.0.1
141 info linkStuff calipers@2.0.1
142 silly linkStuff calipers@2.0.1 has /home/dave/Documents/print-server/node_modules as its parent node_modules
143 silly build poppler-simple@0.2.9
144 info linkStuff poppler-simple@0.2.9
145 silly linkStuff poppler-simple@0.2.9 has /home/dave/Documents/print-server/node_modules as its parent node_modules
146 silly build calipers-pdf@2.0.0
147 info linkStuff calipers-pdf@2.0.0
148 silly linkStuff calipers-pdf@2.0.0 has /home/dave/Documents/print-server/node_modules as its parent node_modules
149 timing action:build Completed in 1ms
150 silly doSerial global-link 34
151 silly doParallel update-linked 0
152 silly doSerial install 34
153 silly install nan@2.11.1
154 info lifecycle nan@2.11.1~install: nan@2.11.1
155 silly install calipers@2.0.1
156 info lifecycle calipers@2.0.1~install: calipers@2.0.1
157 silly install poppler-simple@0.2.9
158 info lifecycle poppler-simple@0.2.9~install: poppler-simple@0.2.9
159 verbose lifecycle poppler-simple@0.2.9~install: unsafe-perm in lifecycle true
160 verbose lifecycle poppler-simple@0.2.9~install: PATH: /home/dave/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dave/Documents/print-server/node_modules/poppler-simple/node_modules/.bin:/home/dave/Documents/print-server/node_modules/.bin:/home/dave/.nvm/versions/node/v8.11.3/bin:/home/dave/bin:/home/dave/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
161 verbose lifecycle poppler-simple@0.2.9~install: CWD: /home/dave/Documents/print-server/node_modules/poppler-simple
162 silly lifecycle poppler-simple@0.2.9~install: Args: [ '-c', '(node-gyp rebuild) || (exit 1)' ]
163 silly lifecycle poppler-simple@0.2.9~install: Returned: code: 1  signal: null
164 info lifecycle poppler-simple@0.2.9~install: Failed to exec install script
165 timing action:install Completed in 547ms
166 verbose unlock done using /home/dave/.npm/_locks/staging-6f19addd09a3193b.lock for /home/dave/Documents/print-server/node_modules/.staging
167 timing stage:rollbackFailedOptional Completed in 8ms
168 timing stage:runTopLevelLifecycles Completed in 2484ms
169 silly saveTree print-server@1.0.0
169 silly saveTree ├─┬ axios@0.18.0
169 silly saveTree │ ├─┬ follow-redirects@1.5.8
169 silly saveTree │ │ └─┬ debug@3.1.0
169 silly saveTree │ │   └── ms@2.0.0
169 silly saveTree │ └── is-buffer@1.1.6
169 silly saveTree ├─┬ calipers-pdf@2.0.0
169 silly saveTree │ ├── bluebird@3.5.2
169 silly saveTree │ └─┬ poppler-simple@0.2.9
169 silly saveTree │   └── nan@2.11.1
169 silly saveTree ├── calipers@2.0.1
169 silly saveTree ├─┬ handlebars@4.0.12
169 silly saveTree │ ├─┬ async@2.6.1
169 silly saveTree │ │ └── lodash@4.17.11
169 silly saveTree │ ├─┬ optimist@0.6.1
169 silly saveTree │ │ ├── minimist@0.0.8
169 silly saveTree │ │ └── wordwrap@0.0.3
169 silly saveTree │ ├── source-map@0.6.1
169 silly saveTree │ └─┬ uglify-js@3.4.9
169 silly saveTree │   └── commander@2.17.1
169 silly saveTree ├─┬ html-pdf-chrome@0.5.0
169 silly saveTree │ ├─┬ chrome-launcher@0.10.5
169 silly saveTree │ │ ├── @types/core-js@0.9.46
169 silly saveTree │ │ ├── @types/mkdirp@0.3.29
169 silly saveTree │ │ ├── @types/node@9.6.32
169 silly saveTree │ │ ├── @types/rimraf@0.0.28
169 silly saveTree │ │ ├── is-wsl@1.1.0
169 silly saveTree │ │ ├─┬ lighthouse-logger@1.1.0
169 silly saveTree │ │ │ ├── debug@2.6.9
169 silly saveTree │ │ │ └── marky@1.2.0
169 silly saveTree │ │ ├── mkdirp@0.5.1
169 silly saveTree │ │ └─┬ rimraf@2.6.2
169 silly saveTree │ │   └─┬ glob@7.1.3
169 silly saveTree │ │     ├── fs.realpath@1.0.0
169 silly saveTree │ │     ├─┬ inflight@1.0.6
169 silly saveTree │ │     │ ├─┬ once@1.4.0
169 silly saveTree │ │     │ │ └── wrappy@1.0.2
169 silly saveTree │ │     │ └── wrappy@1.0.2
169 silly saveTree │ │     ├── inherits@2.0.3
169 silly saveTree │ │     ├─┬ minimatch@3.0.4
169 silly saveTree │ │     │ └─┬ brace-expansion@1.1.11
169 silly saveTree │ │     │   ├── balanced-match@1.0.0
169 silly saveTree │ │     │   └── concat-map@0.0.1
169 silly saveTree │ │     ├── once@1.4.0
169 silly saveTree │ │     └── path-is-absolute@1.0.1
169 silly saveTree │ └─┬ chrome-remote-interface@0.25.7
169 silly saveTree │   ├── commander@2.11.0
169 silly saveTree │   └─┬ ws@3.3.2
169 silly saveTree │     ├── async-limiter@1.0.0
169 silly saveTree │     ├── safe-buffer@5.1.2
169 silly saveTree │     └── ultron@1.1.1
169 silly saveTree ├─┬ mssql@4.2.1
169 silly saveTree │ ├── generic-pool@3.4.2
169 silly saveTree │ └─┬ tedious@2.6.4
169 silly saveTree │   ├─┬ babel-runtime@6.26.0
169 silly saveTree │   │ ├── core-js@2.5.7
169 silly saveTree │   │ └── regenerator-runtime@0.11.1
169 silly saveTree │   ├── big-number@0.3.1
169 silly saveTree │   ├─┬ bl@1.2.2
169 silly saveTree │   │ └─┬ readable-stream@2.3.6
169 silly saveTree │   │   ├── core-util-is@1.0.2
169 silly saveTree │   │   ├── isarray@1.0.0
169 silly saveTree │   │   ├── process-nextick-args@2.0.0
169 silly saveTree │   │   ├── string_decoder@1.1.1
169 silly saveTree │   │   └── util-deprecate@1.0.2
169 silly saveTree │   ├── depd@1.1.2
169 silly saveTree │   ├─┬ iconv-lite@0.4.24
169 silly saveTree │   │ └── safer-buffer@2.1.2
169 silly saveTree │   ├── native-duplexpair@1.0.0
169 silly saveTree │   ├── punycode@2.1.1
169 silly saveTree │   ├── readable-stream@2.3.6
169 silly saveTree │   └── sprintf-js@1.1.1
169 silly saveTree ├─┬ restler@3.4.0
169 silly saveTree │ ├── iconv-lite@0.2.11
169 silly saveTree │ ├── qs@1.2.0
169 silly saveTree │ ├─┬ xml2js@0.4.0
169 silly saveTree │ │ ├── sax@0.5.8
169 silly saveTree │ │ └── xmlbuilder@10.0.0
169 silly saveTree │ └── yaml@0.2.3
169 silly saveTree ├─┬ vasync@2.2.0
169 silly saveTree │ └─┬ verror@1.10.0
169 silly saveTree │   ├── assert-plus@1.0.0
169 silly saveTree │   └── extsprintf@1.4.0
169 silly saveTree ├─┬ winston@3.1.0
169 silly saveTree │ ├─┬ diagnostics@1.1.1
169 silly saveTree │ │ ├─┬ colorspace@1.1.1
169 silly saveTree │ │ │ ├─┬ color@3.0.0
169 silly saveTree │ │ │ │ ├─┬ color-convert@1.9.3
169 silly saveTree │ │ │ │ │ └── color-name@1.1.3
169 silly saveTree │ │ │ │ └─┬ color-string@1.5.3
169 silly saveTree │ │ │ │   └─┬ simple-swizzle@0.2.2
169 silly saveTree │ │ │ │     └── is-arrayish@0.3.2
169 silly saveTree │ │ │ └── text-hex@1.0.0
169 silly saveTree │ │ ├─┬ enabled@1.0.2
169 silly saveTree │ │ │ └── env-variable@0.0.4
169 silly saveTree │ │ └─┬ kuler@1.0.0
169 silly saveTree │ │   └── colornames@1.1.1
169 silly saveTree │ ├── is-stream@1.1.0
169 silly saveTree │ ├─┬ logform@1.10.0
169 silly saveTree │ │ ├── colors@1.3.2
169 silly saveTree │ │ ├── fast-safe-stringify@2.0.6
169 silly saveTree │ │ ├── fecha@2.3.3
169 silly saveTree │ │ ├── ms@2.1.1
169 silly saveTree │ │ └── triple-beam@1.3.0
169 silly saveTree │ ├── one-time@0.0.4
169 silly saveTree │ ├── stack-trace@0.0.10
169 silly saveTree │ ├── triple-beam@1.3.0
169 silly saveTree │ └── winston-transport@4.2.0
169 silly saveTree └── ws@3.3.2
170 warn print-server@1.0.0 No repository field.
171 verbose stack Error: poppler-simple@0.2.9 install: `(node-gyp rebuild) || (exit 1)`
171 verbose stack Exit status 1
171 verbose stack     at EventEmitter.<anonymous> (/home/dave/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
171 verbose stack     at emitTwo (events.js:126:13)
171 verbose stack     at EventEmitter.emit (events.js:214:7)
171 verbose stack     at ChildProcess.<anonymous> (/home/dave/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
171 verbose stack     at emitTwo (events.js:126:13)
171 verbose stack     at ChildProcess.emit (events.js:214:7)
171 verbose stack     at maybeClose (internal/child_process.js:925:16)
171 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
172 verbose pkgid poppler-simple@0.2.9
173 verbose cwd /home/dave/Documents/print-server
174 verbose Linux 4.10.0-38-generic
175 verbose argv "/home/dave/.nvm/versions/node/v8.11.3/bin/node" "/home/dave/.nvm/versions/node/v8.11.3/bin/npm" "i" "--save" "calipers" "calipers-pdf"
176 verbose node v8.11.3
177 verbose npm  v6.4.1
178 error code ELIFECYCLE
179 error errno 1
180 error poppler-simple@0.2.9 install: `(node-gyp rebuild) || (exit 1)`
180 error Exit status 1
181 error Failed at the poppler-simple@0.2.9 install script.
181 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by blackbeam** [comment]
Hi!
Looks like you need to install poppler packages using the package manager of your Linux distribution.
Please look into last two comments of #5

**Comment by blackbeam** [comment]
Closing due to inactivity.
Feel free to reopen if necessary.
